# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spoon And Birdcage
email: spoonandbirdcage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Spoon And Birdcage: Awesome Designs Since 2010 is the portfoilio of Barrett A. Long.
  I would consider myself an all around tecno art geek and I recently receved my masters degree from Alfred University in Fine Arts.
  I am also crazy about puppies (I have a Boston Terrier names Jacques-Yves), coffee, Swans (the band not the animal) and screen printing.
  My most recent design/development projects include Act2Learn.ca and Managen.com, check back often for updates.
  I also run frontslash.xzy which is a blog with lots of tutorials and what not about web design, web development and lots of other fun super geeky things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spoonandbirdcage.com" # the base hostname & protocol for your site
twitter_username: SpoonBirdcage
github_username:  SpoonAndBirdcage

# Build settings
markdown: kramdown

# Excluded/Keep Files
exclude: ['node_modules', 'css', '_scss', 'package.json', 'Gruntfile.js', 'dist']
keep_files: ['_site/css', '_site/assets', '_site/js']

# Permalinks
permalink: :categories/:title
